runmode: debug               # 开发模式, debug, release, test
addr: 127.0.0.1:8080                   # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
log:
  writers: file,stdout
  logger_level: DEBUG             #日志级别 DEBUG、INFO、WARN、ERROR、FATAL
  logger_file: log/apiserver.log  
  log_format_text: false          #true 会输出成 JSON 格式，false 会输出成非 JSON 格式
  rollingPolicy: daily            #可选的有 daily 和 size
  log_rotate_date: 7
  log_rotate_size: 1
  log_backup_count: 7
db:
  name: db_apiserver
  addr: 127.0.0.1:3306
  username: root
  password: chen0923
docker_db:
  name: db_apiserver
  addr: 127.0.0.1:3306
  username: root
  password: chen0923